"""initial db setup with pickleEncodedDict

Revision ID: 21f1ce685d7b
Revises: 
Create Date: 2022-03-07 15:25:42.789683

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '21f1ce685d7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('max_diff_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config', app.models.PickleEncodedDict(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('max_diff_project')
    # ### end Alembic commands ###
