"""empty message

Revision ID: c0e881cb4c46
Revises: 21f1ce685d7b
Create Date: 2022-04-20 14:47:19.797228

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'c0e881cb4c46'
down_revision = '21f1ce685d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config', app.models.PickleEncodedDict(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_group')
    # ### end Alembic commands ###
